### ISSUE TITLE
Have only one global configuration

### ISSUE THREAD

**Issue by jmrk84** [StructuralNeurobiologyLab/SyConn#6]
Instead of having config.ini, configspec.ini and global_params.py, everything should be merged into global_params.py to avoid confusion.

**Comment by pschubert** [comment]
I plan to refactor this in the `yaml_config` branch as follows:
- instead of `ConfigObj` and `global_params.py` we will use a single config file in yaml format
- the default or template configuration will be stored at `SyConn/handler/config/config.yml`
- a `config.yml` file will also be stored in the root of every working directory to allow custom parameters for each data set. All entries which are missing in the custom config will fall-back to the default config at `SyConn/handler/config/config.yml`.

**Comment by pschubert** [comment]
This has been addressed in #20
